config/routes.rb
Rails.application.routes.draw do 
  root 'static_pages#home'
  get '/help', to:'static_pages#help'
  get '/about', to:'static_pages#about'
  get '/contact', to:'static_pages#contact'
	get '/signup', to:'users#new'
  get '/login', to:'sessions#new'
	post '/signup', to:'users#create'
	post '/login', to:'sessions#create'
	delete '/logout', to:'sessions#destroy'
	resources :users do
		member do
			get :following, :followers
		end
	end
	resources :users
	resources :account_activations, only: [:edit]
	resources :password_resets, only: [:new, :create, :edit, :update]
	resources :microposts, only: [:create, :destroy]
	resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
		if logged_in?
			@micropost = current_user.microposts.build
			@feed_items = current_user.feed.paginate(page: params[:page])
		end
  end

  def help
  end

  def about
  end

	def contact
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p><a href = "https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href = "https://railstutorial.jp/#ebook">book</a> and 
  to teach web development with
  <a href = "https://railstutorial.org">Ruby on Rails</a>
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
	<a href = "https://railstutorial.jpcontact">contact page</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title,"Help") %>
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>
  <a href="https://railstutorial.jp/help">Rails Tutorial help page</a>.
	To get help on this sample app, see the
  <a href="https://railstutorial.jp/#ebook"><em>Ruby on Rails Tutorial</em></a>
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
	<div class="row">
		<aside class="col-md-4">
			<section class="user_info">
				<%= render 'shared/user_info' %>
			</section>
			<section class="stats">
				<%= render 'shared/stats' %>
			</section>
			<section class="micropost_form">
				<%= render 'shared/micropost_form' %>
			</section>
		</aside>
		<div class="col-md-8">
			<h3>Micropost Feed</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
<% else %>
	<div class="jumbotron text-center">
  	<h1>Sample App</h1>
  
		<h2>This is the home page for the
  	<a href = "https://railstutorial.jp">Ruby on Rails Tutorial</a>
  	sample application.
  	</h2>

		<h2>筆者がクレジットカードをもっていないため、herokuのアドオンが使用できないためSign up機能は現在使えません</h2>
		<h2>今後勉強を進めていくにあたってherokuのアドオンを追加する予定ですので、それまでお待ち下さい</h2>
		<h2>本アプリを使用するにあたってサンプルユーザーへのログインIDとパスワードを載せておきます</h2>
		<ul style="list-style:none;">
			<li>ID : example@railstutorial.org</li>
			<li>PASSWORD : foobar</li>
		</ul>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	</div>
  <%= link_to image_tag("rails.png", alt:"Rails logo"), 'http://rubyonrails.org/' %>
  <%#= link_to image_tag("kitten.jpg", alt:"This is a Cat") %>

<% end %>